- name: Install nginx
  apt:
    name: nginx
    state: latest
  tags:
    - nginx_install
    - apt

- name: remove default nginx site config
  file: 
    path: /etc/nginx/sites-enabled/default 
    state: absent

- name: template nginx config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: nginx_config.cfg.j2, dest: /etc/nginx/conf.d/video_app.conf }
    - { src: nginx.conf.j2, dest: /etc/nginx/nginx.conf }
  notify:
    - reload nginx
  tags:
    - nginx_deploy

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
